[changelog]
header = ""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
- {% if commit.scope %}**{{ commit.scope }}:** {% endif %}{{ commit.message }}\
{% endfor %}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
commit_parsers = [
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^refactor", group = "Miscellaneous" },
    { message = "^perf", group = "Miscellaneous" },
    { message = "^style", group = "Miscellaneous" },
    { message = "^test", group = "Miscellaneous" },
    { message = "^docs", group = "Miscellaneous" },
    { message = "^build", group = "Miscellaneous" },
    { message = "^ops", group = "Miscellaneous" },
    { message = "^chore", group = "Miscellaneous" },
]
filter_commits = true
tag_pattern = "v[0-9]*"
